// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrwflkqyeuaxtitkugym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxyd2Zsa3F5ZXVheHRpdGt1Z3ltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMzgwNzMsImV4cCI6MjA2MjYxNDA3M30.buJk2ksg7GGpwhoTdKC2mMoqIBpxZrwiz1mMJFg7LOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);